name: Do 2000+ GH contributions/year

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install jq curl -y
      - name: Get total contributions
        uses: octokit/graphql-action@v2.x
        id: get_contributions
        with:
          query: |
            query {
              viewer {
                login
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
      - name: Test if contibution requirement is satisfied
        run: |
          echo "Current total contributions per year: ${{ steps.get_contibutions.outputs.data }}"
