name: Update README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  ongeki:
    name: Retrieve ONGEKI rating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          check-latest: true
      - name: Install dependencies
        run: go install github.com/ericchiang/pup@latest
      - name: Get ONGEKI rating
        id: rating
        run: |
          RATING_TEXT=(`curl -s https://ongeki-score.net/user/4826 | ~/go/bin/pup '.box > table tr:nth-child(5) > td text{}'`)
          RATING=${RATING_TEXT[0]}
          echo "rating=$RATING" >> $GITHUB_OUTPUT
    outputs:
      rating: ${{steps.rating.outputs.rating}}

  chunithm:
    name: Retrieve CHUNITHM rating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          check-latest: true
      - name: Install dependencies
        run: go install github.com/ericchiang/pup@latest
      - name: Get CHUNITHM rating
        id: rating
        run: |
          RATING_TEXT=(`curl -s https://chunirec.net/users/hakatashi | ~/go/bin/pup '.player-profile-container-row:nth-child(3) .player-profile-container-data text{}'`)
          RATING=${RATING_TEXT[0]}
          echo "rating=$RATING" >> $GITHUB_OUTPUT
    outputs:
      rating: ${{steps.rating.outputs.rating}}

  contributions:
    name: Retrieve GitHub contributions
    runs-on: ubuntu-latest
    steps:
      - name: Get total contributions
        uses: octokit/graphql-action@v2.x
        id: get_contributions
        with:
          query: |
            query($owner: String!) {
              user(login: $owner) {
                contributionsCollection {
                  contributionCalendar {
                    totalContributions
                  }
                }
              }
            }
          owner: "hakatashi"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    outputs:
      contributions: ${{fromJSON(steps.get_contributions.outputs.data).user.contributionsCollection.contributionCalendar.totalContributions}}

  update-readme:
    name: Update README.md
    needs:
      - ongeki
      - chunithm
      - contributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update README
        env:
          ONGEKI_RATING: ${{needs.ongeki.outputs.rating}}
          CHUNITHM_RATING: ${{needs.chunithm.outputs.rating}}
          GITHUB_CONTRIBUTIONS: ${{needs.contributions.outputs.contributions}}
        run: |
          cat << EOF > README.md
          [![Being a solid person][solid-img]][solid-link]
          [![Do 2000+ GH contributions/year][contributions-img]][contributions-link]
          [![Write at least one article every month][blog-img]][blog-link]

          [![O.N.G.E.K.I. Rating][ongeki-img]][ongeki-link]
          [![CHUNITHM Rating][chunithm-img]][chunithm-link]
          ![Current Heart Beat Rate][heartbeat-img]
          [![GitHub Contributions][contributions-count-img]][contributions-count-link]

          [solid-img]: https://github.com/hakatashi/hakatashi/workflows/Being%20a%20solid%20person/badge.svg
          [solid-link]:https://github.com/hakatashi/hakatashi/actions?query=workflow%3A%22Being+a+solid+person%22
          [contributions-img]: https://github.com/hakatashi/hakatashi/actions/workflows/contributions.yml/badge.svg
          [contributions-link]: https://github.com/hakatashi/hakatashi/actions/workflows/contributions.yml
          [blog-img]: https://github.com/hakatashi/hakatashi/actions/workflows/blog.yml/badge.svg
          [blog-link]: https://github.com/hakatashi/hakatashi/actions/workflows/blog.yml
          [ongeki-img]: https://img.shields.io/badge/O.N.G.E.K.I.-$ONGEKI_RATING-blue
          [ongeki-link]: https://ongeki-score.net/user/4826
          [chunithm-img]: https://img.shields.io/badge/CHUNITHM-$CHUNITHM_RATING-blue
          [chunithm-link]: https://chunirec.net/users/hakatashi
          [heartbeat-img]: https://img.shields.io/endpoint?url=https%3A%2F%2Fus-central1-hakatabot-firebase-functions.cloudfunctions.net%2FfitbitLatestHeartBeatRate&cacheSeconds=3600
          [contributions-count-img]: https://img.shields.io/badge/Contributions-$GITHUB_CONTRIBUTIONS-orange
          [contributions-count-link]: https://github.com/hakatashi
          EOF
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[AUTO] Update README.md"
